### ISSUE TITLE
Could not resolve substitution to a value: ${akka.stream.materializer}

### ISSUE THREAD

**Issue by MayJV** [teeyog/IQL#3]
您好，执行得时候报错

Exception in thread "main" com.typesafe.config.ConfigException$UnresolvedSubstitution: reference.conf @ jar:file:/home/zhangxin/iql-engine-1.0-SNAPSHOT-jar-with-dependencies.jar!/reference.conf: 846: Could not resolve substitution to a value: ${akka.stream.materializer}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow

执行命令

spark-submit \
--name IQL \
--master local \
--deploy-mode client \
--conf spark.executor.extraJavaOptions="-Xms1024m  -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m" \
--num-executors 1 \
--driver-memory 3G \
--executor-memory 1g \
--class iql.engine.main.IqlMain \
iql-engine-1.0-SNAPSHOT-jar-with-dependencies.jar

**Comment by teeyog** [comment]
@MayJV I'm sorry to reply to you now. You can pull  the latest code to solve this problem, just change the way of maven packaging.
